image: openjdk7
env:
  - GOPATH=/var/cache/drone
script:
  - sudo aptitude install maven
  - mvn clean install
deploy:
    bash:
        command: /bin/ls
notify:
  email:
    recipients:
      - eric.robibaro@radialpoint.com
